# Generated by Django 3.1.5 on 2021-01-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tnx_type',
            field=models.CharField(choices=[('deposit', 'Зачисление на аккаунт пользователя'), ('expense', 'Списание за услуги с аккаунта пользователя'), ('withdraw', 'Вывод средств с аккаунта пользователя во вне'), ('cancellation ', 'Пополнение счета, средствами с отмены списания')], max_length=32, verbose_name='Тип транзакции'),
        ),
    ]
