# Generated by Django 3.1.6 on 2021-02-14 20:26

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0005_auto_20210121_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('mdate', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order_id', models.UUIDField(default=uuid.UUID('a28302f4-5146-41b7-9bda-61362bd8f402'), verbose_name='Уникальный номер заказа')),
                ('status', models.CharField(choices=[('not_payed', 'Не оплачен'), ('payed', 'Оплачен'), ('partpayed', 'Частично оплачен'), ('pending', 'Ждем подтверждения оплаты'), ('failed', 'Оплата не успешна'), ('cancelled', 'Оплата отмененна')], default='not_payed', max_length=32, verbose_name='Статус платежа')),
                ('payment_system', models.CharField(choices=[('dummy', 'Псевдо платежная система')], default='dummy', max_length=64, verbose_name='Тип платежной системы')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Ожидаймые средства')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19, verbose_name='Пришедшие средства')),
                ('payed_date', models.DateTimeField(null=True, verbose_name='Время оплаты')),
                ('req_date', models.DateTimeField(null=True, verbose_name='Время оплаты')),
                ('data', models.JSONField(verbose_name='Информация от платежной системы')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.bill', verbose_name='Счет завершения оплаты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец транзакции')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
