# Generated by Django 3.1.6 on 2021-02-14 20:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Уникальный номер заказа'),
        ),
    ]
