# Generated by Django 3.1.6 on 2021-02-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20210214_2040'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='billing_pay_order_i_f4ba75_idx'),
        ),
    ]
