# Generated by Django 3.1.5 on 2021-01-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=128)),
                ('inn', models.CharField(max_length=50)),
                ('kpp', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('bik', models.CharField(max_length=50)),
                ('real_address', models.CharField(max_length=50)),
                ('billing_address', models.CharField(max_length=128, verbose_name='description if this field?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.client')),
            ],
        ),
    ]
