# Generated by Django 3.1.5 on 2021-01-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0002_clientdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdata",
            name="billing_address",
            field=models.CharField(max_length=128),
        ),
    ]
