# Generated by Django 3.1.5 on 2021-01-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0007_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="buy_price",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_price",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
