# Generated by Django 3.1.5 on 2021-01-31 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_auto_20210121_0941"),
        ("auction", "0008_auto_20210114_1704"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("inn", models.CharField(max_length=10)),
                ("vat", models.IntegerField(verbose_name="НДС")),
                (
                    "is_vat_active",
                    models.BooleanField(verbose_name="Включен НДС"),
                ),
                ("cdate", models.DateTimeField(auto_now_add=True)),
                ("mdate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdate",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "mdate",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        verbose_name="Сумма сделки",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DealBill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cdate",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "mdate",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
            },
        ),
        migrations.RenameField(
            model_name="client",
            old_name="activated",
            new_name="is_admin",
        ),
        migrations.RemoveField(
            model_name="client",
            name="company_id",
        ),
        migrations.AddField(
            model_name="client",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активная ставка"),
                    ("deleted", "Удаленная ставка"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="buy_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_price",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активный"),
                    ("inactive", "Не активный"),
                    ("deleted", "Удаленный"),
                    ("sold", "Проданный"),
                    ("canceled", "Отменен"),
                ],
                default="inactive",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["price"], name="auction_bid_price_9fa9b5_idx"
            ),
        ),
        migrations.AddField(
            model_name="dealbill",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.bill",
                verbose_name="Счет",
            ),
        ),
        migrations.AddField(
            model_name="dealbill",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auction.deal",
                verbose_name="Сделка",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="bills",
            field=models.ManyToManyField(
                through="auction.DealBill", to="billing.Bill"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="auction.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auction.company",
            ),
        ),
    ]