# Generated by Django 3.1.5 on 2021-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20210114_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='activated',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
