# Generated by Django 3.1.6 on 2021-02-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_insert_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='face_id',
            field=models.IntegerField(choices=[('1', 'Физ лицо'), ('2', 'Юр лицо'), ('3', 'ИП'), ('4', 'Бюджет')], default='1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
