# Generated by Django 3.1.6 on 2021-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20210214_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
