# Generated by Django 3.1.5 on 2021-01-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20210114_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
    ]
