# Generated by Django 3.1.5 on 2021-01-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20210114_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_staff',
        ),
    ]
