# Generated by Django 3.1.5 on 2021-01-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_auto_20210116_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=10)),
                ('vat', models.IntegerField(verbose_name='НДС')),
                ('is_vat_active', models.BooleanField(verbose_name='Включен НДС')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
