# Generated by Django 3.1.5 on 2021-01-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_auto_20210121_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_id',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.company'),
        ),
    ]
