# Generated by Django 3.1.5 on 2021-01-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0021_auto_20210121_1819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="auction.product",
                verbose_name="Товар",
            ),
        ),
    ]
