# Generated by Django 3.1.5 on 2021-01-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_auto_20210124_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('deleted', 'Удаленный')], default='active', max_length=32),
        ),
    ]
