# Generated by Django 3.1.5 on 2021-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_auto_20210125_1110'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['price'], name='auction_bid_price_9fa9b5_idx'),
        ),
    ]
